Cleanup and pre release 1.3.0
hyperhq/hypernetes pull request #142
Opened 2016-09-18 15:56 UTC by resouer

1. Remove http hyper client  functions
2. Timeout of context, will fix: https://github.com/hyperhq/hypernetes/issues/135
3. Clean up types

cc @feiskyer

2016-09-18 16:16 UTC, feiskyer commented on pkg/kubelet/hyper/hyperclient.go
> +	ctx, cancel := getContextWithTimeout(hyperContextTimeout)
`hyperContextTimeout` maybe too short for image pulling, use a longer timeout instead for `PullImage`.

2016-09-18 16:18 UTC, feiskyer commented on pkg/kubelet/hyper/hyperclient.go
> +	stream, err := c.client.Attach(ctx)
Should use `context.Background()` instead because we can't predict how long will users interact with containers.

2016-09-18 16:18 UTC, feiskyer commented on pkg/kubelet/hyper/hyperclient.go
> +	stream, err := c.client.ExecStart(ctx)
Same with attach above.

2016-09-18 16:19 UTC, feiskyer requested changes

2016-09-19 01:59 UTC, resouer commented on pkg/kubelet/hyper/hyperclient.go
> +	ctx, cancel := getContextWithTimeout(hyperContextTimeout)
We can not expect how long it will take to pull image, maybe do not use timeout ctx here?

2016-09-19 02:12 UTC, feiskyer commented on pkg/kubelet/hyper/hyperclient.go
> +	ctx, cancel := getContextWithTimeout(hyperContextTimeout)
@resouer Try report status same with https://github.com/kubernetes/frakti/pull/26?

2016-09-19 05:41 UTC, resouer commented on pkg/kubelet/hyper/hyperclient.go
> +	stream, err := c.client.Attach(ctx)
getContextWithTimeout already returned `context.Background`

2016-09-19 07:12 UTC, resouer commented
@feiskyer updated with a timeout checker of pull image

2016-09-19 07:58 UTC, feiskyer approved these changes

2016-09-19 07:58 UTC, feiskyer commented
LGTM

2016-09-19 07:58 UTC, merged