add service files
hyperhq/hypernetes pull request #152
Opened 2016-10-09 09:15 UTC by xlgao-zju

close #149 

Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>

2016-10-09 09:18 UTC, feiskyer requested changes

2016-10-09 09:18 UTC, feiskyer commented on hack/hypernetes/hypernetes.sh
> +Requires=docker.service
we don't require docker. those two lines should be removed.

2016-10-10 07:00 UTC, xlgao-zju commented on hack/hypernetes/hypernetes.sh
> +Requires=docker.service
OK. But I will take some time to test this pr because of the poor network environment.

2016-10-10 07:09 UTC, feiskyer commented on hack/hypernetes/hypernetes.sh
> +Requires=docker.service
@xlgao-zju Yep, network is a big problem. Thanks for the work.

2016-10-10 12:05 UTC, xlgao-zju commented
@feiskyer updated. And it seems fine on centos 7.2.

2016-10-11 02:54 UTC, feiskyer approved these changes

2016-10-11 02:55 UTC, feiskyer commented
Cool, thanks.

2016-10-11 02:56 UTC, merged